# Generated by Django 3.1.6 on 2021-04-16 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='SOME STRING', max_length=100)),
                ('author', models.CharField(default='SOME STRING', max_length=100)),
                ('email', models.EmailField(default='SOME STRING', max_length=100)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.PositiveIntegerField()),
                ('product_code', models.CharField(default='SOME STRING', max_length=100)),
                ('product_name', models.CharField(default='SOME STRING', max_length=50)),
                ('product_desc', models.CharField(default='SOME STRING', max_length=100)),
                ('specifications', models.CharField(default='SOME STRING', max_length=100)),
                ('manufacturer_id', models.PositiveIntegerField()),
                ('substrate_manufacturer', models.CharField(default='SOME STRING', max_length=50)),
                ('substrate_type', models.CharField(default='SOME STRING', max_length=50)),
                ('superstate_manufacturer', models.CharField(default='SOME STRING', max_length=50)),
                ('superstate_type', models.CharField(default='SOME STRING', max_length=50)),
                ('interconnect_supplier', models.CharField(default='SOME STRING', max_length=50)),
                ('interconnect_material', models.CharField(default='SOME STRING', max_length=50)),
                ('fuse_rating', models.PositiveIntegerField()),
                ('bypass_diodes', models.PositiveIntegerField()),
                ('series_strings', models.PositiveIntegerField()),
                ('cells_series', models.PositiveIntegerField()),
                ('total_cells', models.PositiveIntegerField()),
                ('cell_technology', models.CharField(default='SOME STRING', max_length=50)),
                ('cell_area', models.PositiveIntegerField()),
                ('weight', models.PositiveIntegerField()),
                ('width', models.PositiveIntegerField()),
                ('rated_voc', models.CharField(default='SOME STRING', max_length=100)),
                ('rated_isc', models.CharField(default='SOME STRING', max_length=100)),
                ('rated_vmp', models.CharField(default='SOME STRING', max_length=100)),
                ('rated_imp', models.CharField(default='SOME STRING', max_length=100)),
                ('rated_pmp', models.CharField(default='SOME STRING', max_length=100)),
                ('rated_ff', models.CharField(default='SOME STRING', max_length=100)),
                ('length_str', models.CharField(default='SOME STRING', max_length=30)),
            ],
        ),
    ]
