# Generated by Django 3.1.6 on 2021-04-17 23:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_testsequence'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(default='Service 1', max_length=100)),
                ('service_desc', models.CharField(default='Service Description', max_length=100)),
                ('is_fi_required', models.BooleanField(default=True)),
                ('fi_frequency', models.CharField(default='FI Frequency', max_length=100)),
                ('standard', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='backend.teststandard')),
            ],
        ),
    ]
