# Generated by Django 3.1.6 on 2021-04-18 00:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_service'),
    ]

    operations = [
        migrations.CreateModel(
            name='PerformanceData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_system_voltage', models.DecimalField(decimal_places=3, default=0, max_digits=7)),
                ('voc', models.DecimalField(decimal_places=3, default=0, max_digits=7)),
                ('isc', models.DecimalField(decimal_places=3, default=0, max_digits=7)),
                ('vmp', models.DecimalField(decimal_places=3, default=0, max_digits=7)),
                ('imp', models.DecimalField(decimal_places=3, default=0, max_digits=7)),
                ('pmp', models.DecimalField(decimal_places=3, default=0, max_digits=7)),
                ('ff', models.DecimalField(decimal_places=3, default=0, max_digits=7)),
                ('product', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='backend.product')),
                ('test_sequence', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='backend.testsequence')),
            ],
        ),
    ]
