# Generated by Django 3.1.6 on 2021-04-18 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_performancedata'),
    ]

    operations = [
        migrations.AddField(
            model_name='performancedata',
            name='description',
            field=models.CharField(default='SOME STRING', max_length=100),
        ),
    ]
