# Generated by Django 3.1.6 on 2021-04-18 00:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_performancedata_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default='SOME STRING', max_length=30)),
                ('middle_name', models.CharField(default='SOME STRING', max_length=30)),
                ('last_name', models.CharField(default='SOME STRING', max_length=30)),
                ('job_title', models.CharField(default='SOME STRING', max_length=30)),
                ('email', models.CharField(default='SOME STRING', max_length=30)),
                ('office_phone', models.CharField(default='SOME STRING', max_length=10)),
                ('cell_phone', models.CharField(default='SOME STRING', max_length=10)),
                ('prefix', models.CharField(default='SOME STRING', max_length=10)),
                ('client', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='backend.client')),
            ],
        ),
    ]
