# Generated by Django 3.1.6 on 2021-04-18 00:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_number', models.CharField(default='SOME STRING', max_length=10)),
                ('issue_date', models.DateTimeField(auto_now_add=True)),
                ('location', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='backend.location')),
                ('product', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='backend.product')),
                ('standard', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='backend.teststandard')),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='backend.user')),
            ],
        ),
    ]
