# Generated by Django 3.1.6 on 2021-03-01 23:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api_basic', '0002_a'),
    ]

    operations = [
        migrations.AddField(
            model_name='a',
            name='name',
            field=models.CharField(default='SOME STRING', max_length=100),
        ),
        migrations.AddField(
            model_name='article',
            name='author',
            field=models.CharField(default='SOME STRING', max_length=100),
        ),
        migrations.AddField(
            model_name='article',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='article',
            name='email',
            field=models.EmailField(default='SOME STRING', max_length=100),
        ),
        migrations.AddField(
            model_name='article',
            name='title',
            field=models.CharField(default='SOME STRING', max_length=100),
        ),
    ]
