# Generated by Django 3.1.6 on 2021-03-02 01:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_basic', '0003_auto_20210301_2349'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='a',
            name='name',
        ),
    ]
